aurpkg: Delete a useless loop

diff --git a/aurpkg b/aurpkg
--- a/aurpkg
+++ b/aurpkg
@@ -287,94 +287,92 @@ aurpkg_cleanup
 
 # The scripty part
 if [[ ${1} != "" ]]; then
-	while [[ $# -ge 1 ]]; do
-		case "${1}" in
+	case "${1}" in
 
-			# Helping menu
-			"-h" | "--help")
-			shift
-				aurpkg_help;;
-				
-			# Version infos
-			"--version" | "--about" | "-v")
-			shift
-				aurpkg_version;;
+		# Helping menu
+		"-h" | "--help")
+		shift
+			aurpkg_help;;
 
-			# Installing
-			"-S" | "--sync" | "--install")
-			shift
-				if [[ ${1} == "" ]]; then
-					echo "Fatal: No package specified";
-					exit 1;
-				else
-					while [[ $# -ge 1 ]]; do
-						aurpkg_install "${1}";
-					shift
-					done
-				fi;;
+		# Version infos
+		"--version" | "--about" | "-v")
+		shift
+			aurpkg_version;;
 
-			# Uninstall/remove
-			"-R" | "--remove" | "--uninstall")
-			shift
+		# Installing
+		"-S" | "--sync" | "--install")
+		shift
+			if [[ ${1} == "" ]]; then
+				echo "Fatal: No package specified";
+				exit 1;
+			else
+				while [[ $# -ge 1 ]]; do
+					aurpkg_install "${1}";
+				shift
+				done
+			fi;;
 
-				if [[ ${1} == "" ]]; then
-					echo "Fatal: No package specified";
-					exit 1;
-				else
-					while [[ $# -ge 1 ]]; do
-						aurpkg_uninstall "${1}";
-					shift
-					done
-				fi;;
+		# Uninstall/remove
+		"-R" | "--remove" | "--uninstall")
+		shift
 
-			# Update
-			"-U" | "--update" | "--upgrade")
-			shift
+			if [[ ${1} == "" ]]; then
+				echo "Fatal: No package specified";
+				exit 1;
+			else
+				while [[ $# -ge 1 ]]; do
+					aurpkg_uninstall "${1}";
+				shift
+				done
+			fi;;
 
-				if [[ ${1} == "" ]]; then
-					echo "Fatal: No package specified";
-					exit 1;
-				elif [[ ${1} == "ALL" ]]; then
-					aurpkg_full_update;
-				else
-					while [[ $# -ge 1 ]]; do
-						aurpkg_update "${1}";
-					shift
-					done
-				fi;;
-				
-			# Search
-			"-Ss" | "-s" | "--search")
-			shift
-			
-				if [[ ${1} == "" ]]; then
-					echo "No query specified";
-					exit 1;
-				else
-					PKG=${1};
-					aurpkg_search;
-				fi;;
+		# Update
+		"-U" | "--update" | "--upgrade")
+		shift
 
-			"-i" | "--info")
-			shift
-				if [[ ${1} == "" ]]; then
-					echo "Fatal: No package specified";
-					exit 1;
-				else
-					while [[ $# -ge 1 ]]; do
-						PKG="${1}";
-						aurpkg_info;
-					shift
-					done
-				fi;;
+			if [[ ${1} == "" ]]; then
+				echo "Fatal: No package specified";
+				exit 1;
+			elif [[ ${1} == "ALL" ]]; then
+				aurpkg_full_update;
+			else
+				while [[ $# -ge 1 ]]; do
+					aurpkg_update "${1}";
+				shift
+				done
+			fi;;
 
-			# If no command matches
-			*)
-				echo "Invalid command";
-				echo "Type aurpkg --help for a list of the commands";;
-		esac
-	shift
-	done
+		# Search
+		"-Ss" | "-s" | "--search")
+		shift
+
+			if [[ ${1} == "" ]]; then
+				echo "No query specified";
+				exit 1;
+			else
+				PKG=${1};
+				aurpkg_search;
+			fi;;
+
+		"-i" | "--info")
+		shift
+			if [[ ${1} == "" ]]; then
+				echo "Fatal: No package specified";
+				exit 1;
+			else
+				while [[ $# -ge 1 ]]; do
+					PKG="${1}";
+					aurpkg_info;
+				shift
+				done
+			fi;;
+
+		# If no command matches
+		*)
+		shift
+			echo "Invalid command";
+			echo "Type aurpkg --help for a list of the commands";;
+	esac
 else
 	echo "Invalid command";
 	echo "Type aurpkg --help for a list of the commands";
